model:
  llm_type: openai # cohere, openai, hf
  llm: gpt-4o-mini # command-r, gpt-4o, hf

apikeys:
  cohere: 
  openai:
  huggingface: 
  anthropic:

paths:
  cache_dir: ./


seed: 42
top_p: 0.9
batch_size: 1024
temperature: 0.3
retriever_top : 5
max_tokens: 16
max_new_tokens: 16
use_vllm: False
gpu_util: 0.85
num_gpu: 1